name: Deploy Web Pages to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'www/**' # केवल www फ़ोल्डर में बदलाव होने पर ही यह चलेगा

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'www' # सीधे www फोल्डर को पब्लिश करेगा

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
